### ISSUE TITLE
java.lang.ClassCastException: org.crosswalk.engine.XWalkCordovaView cannot be cast to android.webkit.WebView

### ISSUE THREAD

**Issue by MeAntonio** [crosswalk-project/cordova-plugin-crosswalk-webview#170]
Adding crosswalk into my project brakes some functions in pohneRTC

E/AndroidRuntime( 7115):        at com.dooble.phonertc.PhoneRTCPlugin.createVideoView(PhoneRTCPlugin.java:389)
E/AndroidRuntime( 7115):        at com.dooble.phonertc.PhoneRTCPlugin.refreshVideoView(PhoneRTCPlugin.java:420)
E/AndroidRuntime( 7115):        at com.dooble.phonertc.PhoneRTCPlugin.addRemoteVideoTrack(PhoneRTCPlugin.java:344)
E/AndroidRuntime( 7115):        at com.dooble.phonertc.Session$PCObserver$2.run(Session.java:284)
E/AndroidRuntime( 7115):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 7115):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7115):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7115):        at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 7115):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7115):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7115):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime( 7115):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime( 7115):        at dalvik.system.NativeStart.main(Native Method)

Here are the fucntions:

private void createVideoView() {
		Point size = new Point();
		size.set((int)(_videoConfig.getContainer().getWidth() * _videoConfig.getDevicePixelRatio()),
				(int)(_videoConfig.getContainer().getHeight() * _videoConfig.getDevicePixelRatio()));

		_videoView = new VideoGLView(cordova.getActivity(), size);
		VideoRendererGui.setView(_videoView, null);

		((WebView) webView.getView()).addView(_videoView, _videoParams);
	}

private void refreshVideoView() {
                ........................
                if (_videoView != null) {
			((WebView) webView.getView()).removeView(_videoView);
			_videoView = null;
		}
                ........................
        }

The problem is obviously taht webView and xwalk webView are not the same type. I'm still trying to understand fully what I'm supposed to do, so any help is welcome :)

**Comment by jpike88** [comment]
This is really PhoneRTC's problem, not crosswalk's. They shouldn't be assuming it's a WebView.
