### ISSUE TITLE
RuntimeException: Crosswalk's APIs are not ready yet

### ISSUE THREAD

**Issue by dpa99c** [crosswalk-project/cordova-plugin-crosswalk-webview#184]
Fatal Exception: java.lang.RuntimeException: Crosswalk's APIs are not ready yet
           at org.xwalk.core.XWalkView.setZOrderOnTop(XWalkView.java:1569)
           at org.crosswalk.engine.XWalkWebViewEngine.initWebViewSettings(XWalkWebViewEngine.java:200)
           at org.crosswalk.engine.XWalkWebViewEngine.access$000(XWalkWebViewEngine.java:59)
           at org.crosswalk.engine.XWalkWebViewEngine$2.run(XWalkWebViewEngine.java:96)
           at org.xwalk.core.XWalkActivityDelegate.onActivateCompleted(XWalkActivityDelegate.java:172)
           at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:349)
           at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:317)
           at android.os.AsyncTask.finish(AsyncTask.java:660)
           at android.os.AsyncTask.-wrap1(AsyncTask.java)
           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:154)
           at android.app.ActivityThread.main(ActivityThread.java:6682)
           at java.lang.reflect.Method.invoke(Method.java)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
           
This is accounting for 58% of crashes in my Android app according to Crashlytics. 

Full crash log: [issue_9_crash.log](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/files/1478532/issue_9_crash.log)

**Comment by cosmopolit** [comment]
Same here for 2.3.0. Four crashes in one week.

**Comment by jahk88** [comment]
Hello there, has anyone found a workaround to this issue? Please let me know if you did find a fix to this. Thanks.

**Comment by 2xSamurai** [comment]
> Hello there, has anyone found a workaround to this issue? Please let me know if you did find a fix to this. Thanks.

@jahk88 By any chance did you find a fix for this. I am also facing the same thing on multiple devices.

**Comment by 2xSamurai** [comment]
@cosmopolit Have you found any fix for this. Thank you.

**Comment by boanascimento** [comment]
Does someone has resolved the issue?

**Comment by boanascimento** [comment]
Has someone resolved the issue?

**Comment by dpa99c** [comment]
Both this plugin and the Crosswalk project are deprecated and no longer maintained. 
Therefore it's highly unlikely this will ever be fixed.

**Comment by boanascimento** [comment]
Ok, thanks!
