### ISSUE TITLE
Binary XML file line #20: Error inflating class org.xwalk.core.XWalkView

### ISSUE THREAD

**Issue by shcherbuk96** [crosswalk-project/cordova-plugin-crosswalk-webview#219]
My app work in all version Android except Android 8.0.

```
Process: com.hodite.com.shcherbuk, PID: 1778
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hodite.com.shcherbuk/com.hodite.com.shcherbuk.WebActivity.WebActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class org.xwalk.core.XWalkView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class org.xwalk.core.XWalkView
     Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class org.xwalk.core.XWalkView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.hodite.com.shcherbuk.WebActivity.WebActivity.onCreate(WebActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{da07273 1778:com.hodite.com.shcherbuk/u0a68} (pid=1778, uid=10068) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:54)
        at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:1882)
        at org.xwalk.core.XWalkView.<init>(XWalkView.java:305)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.hodite.com.shcherbuk.WebActivity.WebActivity.onCreate(WebActivity.java:55) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{da07273 1778:com.hodite.com.shcherbuk/u0a68} (pid=1778, uid=10068) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.os.Parcel.readException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1888)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1924)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1913)
        at org.xwalk.core.internal.extension.api.contacts.Contacts.<init>(Contacts.java:42)
        at org.xwalk.core.internal.extension.BuiltinXWalkExtensions.load(BuiltinXWalkExtensions.java:51)
        at org.xwalk.core.internal.XWalkViewInternal.initXWalkContent(XWalkViewInternal.java:464)
        at org.xwalk.core.internal.XWalkViewBridge.<init>(XWalkViewBridge.java:76)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:48)
```
Layout WebActivity:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/main_background"
    tools:context="com.hodite.com.shcherbuk.WebActivity.WebActivity">
    <android.support.design.widget.BottomNavigationView
        android:id="@+id/main_navigation_bottom_navigation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@color/main_background"
        app:itemIconTint="@color/nav_color_list"
        app:itemTextColor="@color/nav_color_list"
        app:menu="@menu/main_menu"/>

    <org.xwalk.core.XWalkView
        android:id="@+id/web_xwalkview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/main_navigation_bottom_navigation_view">

        <ImageView
            android:id="@+id/refresh"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:visibility="invisible"
            app:srcCompat="@drawable/refresh" />

    </org.xwalk.core.XWalkView>

</RelativeLayout>

```
Support me, please

**Comment by shcherbuk96** [comment]
Guys, I decides this problem)
Need update version library and all

**Comment by kmudov** [comment]
Hello shcherbuk96, can you please provide more details how do you succeed to resolve this problem?

**Comment by mkorganashvili** [comment]
@shcherbuk96 please help us solve same problem

**Comment by shcherbuk96** [comment]
Update library. Gradle dont see new version this library. Check new version
this library and update her. It help me.

ср, 20 июня 2018 г., 18:12 mkorganashvili <notifications@github.com>:

**Comment by mkorganashvili** [comment]
I had the same problem and solved by setting xwalkVersion to 23+

`    <preference name="xwalkVersion" value="23+" />
`

**Comment by shcherbuk96** [comment]
Use specific version

ср, 20 июня 2018 г., 19:55 mkorganashvili <notifications@github.com>:

**Comment by nitin123sangani** [comment]
i have try with android studio and i write compile line like compile(name: 'xwalk_core_library', ext: 'aar')
But crash when targetsdk 26 and above can you please help me to resolve error ?

**Comment by shcherbuk96** [comment]
I don't know this problem

ср, 4 июл. 2018 г. в 8:29, nitin123sangani <notifications@github.com>:

**Comment by stuhowarth** [comment]
I am having the same problem. To help decipher it, it seems to be a permissions-based problem that is associated with SDK 26+. These versions require you to manually show a permission dialogue box when a permission is required. 

Now the issue is for some reason I believe Crosswalk is asking for READ_CONTACTS and WRITE_CONTACTS when it initialises when the app is on the splash screen. Ass soon as the splash screen disappears the app crashes because those permissions are not granted. If I force an install via ADB that grants all permissions on install the app works fine. I believe to have narrowed this down to Crosswalk. I am using 2.4.0. I don't even need these permissions as the app doesn't require access to the user's contacts so I'm not sure why this is an issue.

I can change the targetSDKVersion to 24 and it works fine again, however, Google is preventing any app updates in November that do not target at least version 26 and above so this is something that is of concern because if I target 26 then any device running Android 8.0.0 basically crashes on the app loading.

Does this make sense?

**Comment by flashmediasolutions** [comment]
@stuhowarth  I am having the exact same issue. I have gone through the logs as well.

I have noticed that the suggested fix is to add to the AndroidManifest.xml

<uses-permission android:name="android.permission.READ_CONTACTS" />
<uses-permission android:name="android.permission.WRITE_CONTACTS" /> 

But when I run Android again with emulator, same problem. 

I find it hard to believe that this isn't a common issue.

Please reply if you find a fix, I will do the same.

**Comment by rkistner** [comment]
Make sure you update to the latest Crosswalk version (23.53.589.4). If that doesn't fix it, you likely have a different issue.

**Comment by stuhowarth** [comment]
I believe we had the latest version of crosswalk. Anyway removing Crosswalk appeared to fix the issue and we are now able to publish with the latest target SDK which meets Google's impending requirement to ensure you target at least 26. After testing we haven't really noticed any issues with taking Crosswalk out.

**Comment by sundeeprs** [comment]
Having same problem....
fatal error : Unable to start activity ComponentInfo{xxxxxxx.com.xxx.integratedcoe/com.xxxxxxxxx.app.service.Authentication}: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class org.xwalk.core.XWalkView
    java.lang.RuntimeException: Unable to start activity ComponentInfo{XXXXXX.com.XXXXXX.integratedcoe/com.XXXXXX.app.service.Authentication}: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class org.xwalk.core.XWalkView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3041)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6960)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class org.xwalk.core.XWalkView
     Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class org.xwalk.core.XWalkView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:469)
        at android.app.Activity.setContentView(Activity.java:2794)
        at com.XXXXXX.app.service.Authentication.onCreate(Authentication.java:73)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3041)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6960)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:54)
        at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:2082)
        at org.xwalk.core.XWalkView.<init>(XWalkView.java:299)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:469) 
        at android.app.Activity.setContentView(Activity.java:2794) 
        at com.xxxxxxx.app.service.Authentication.onCreate(Authentication.java:73) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3041) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6960) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
     Caused by: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
        at android.view.View.setBackground(View.java:21717)
        at android.view.View.setBackgroundColor(View.java:21679)
        at org.chromium.content.browser.ContentViewRenderView.initTextureView(ContentViewRenderView.java:68)
2018-11-28 11:19:51.500 25897-26116/? E/ACRA:     at org.chromium.content.browser.ContentViewRenderView.<init>(ContentViewRenderView.java:145)
        at org.xwalk.core.internal.XWalkContent$2.<init>(XWalkContent.java:191)
        at org.xwalk.core.internal.XWalkContent.setNativeContent(XWalkContent.java:191)
        at org.xwalk.core.internal.XWalkContent.<init>(XWalkContent.java:151)
        at org.xwalk.core.internal.XWalkViewInternal.initXWalkContent(XWalkViewInternal.java:383)
        at org.xwalk.core.internal.XWalkViewBridge.<init>(XWalkViewBridge.java:72)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:48)
        	... 28 more
2018-11-28 11:19:51.500 25897-26116/? I/ACRA: Finishing the last Activity prior to killing the Process
2018-11-28 11:19:51.521 25897-26116/? I/ACRA: Finished class com.xxxxxxx.app.service.Authentication
2018-11-28 11:19:51.522 25897-26116/? I/Process: Sending signal. PID: 25897 SIG: 9

minSdkVersion 16
targetSdkVersion 26

Updated XWALK version to ( implementation 'org.xwalk:xwalk_core_library-23.53.589.4@aar')
in build.gradle, but it did not worked. Please suggest if you have any other solution or what i am doing wrong?

**Comment by sundeeprs** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:orientation="vertical"
android:layout_width="fill_parent"
android:layout_height="fill_parent"
android:background="#ffffff"
    android:gravity="fill_vertical">

    <org.xwalk.core.XWalkView
        android:id="@+id/web"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:background="#ffffff"
        android:visibility="visible"
        />
</LinearLayout>

**Comment by jahk88** [comment]
Hello everyone, @sundeeprs have you found a solution to your issue? I'm getting the same issue.

**Comment by Hala-Nearmotion** [comment]
@jahk88 the same is here :/ 
have you found a solution?
