### ISSUE TITLE
App will shut down on Android 8.0 or later

### ISSUE THREAD

**Issue by pavane90** [crosswalk-project/cordova-plugin-crosswalk-webview#246]
Hello.
I have a problem running the app on Android 8.0 or later.

Cordova CLI: 7.1.0
Ionic CLI Version: 1.7.16
OS: Mac OS X El Capitan
Cordova android: 6.2.1
cordova-plugin-crosswalk-webview 2.4.0
targetSDKVersion: 26

This error occurs when I start the app.

```bash
04-01 15:43:35.037 14496 14496 E AndroidRuntime: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{22b8b64 14496:jp.co.XXXXXX.YYYY/u0a415} (pid=14496, uid=10415) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:67)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.XWalkCoreWrapper.handlePostInit(XWalkCoreWrapper.java:157)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:306)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:277)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{22b8b64 14496:jp.co.XXXXXX.YYYY/u0a415} (pid=14496, uid=10415) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:54)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:1650)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	... 12 more
04-01 15:43:35.037 14496 14496 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{22b8b64 14496:jp.co.XXXXXX.YYYY/u0a415} (pid=14496, uid=10415) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1967)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1913)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:788)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1930)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1919)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.internal.extension.api.contacts.Contacts.<init>(Contacts.java:42)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.internal.extension.BuiltinXWalkExtensions.load(BuiltinXWalkExtensions.java:51)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.internal.XWalkViewInternal.initXWalkContent(XWalkViewInternal.java:381)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.internal.XWalkViewInternal.<init>(XWalkViewInternal.java:273)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.internal.XWalkViewBridge.<init>(XWalkViewBridge.java:64)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:48)
04-01 15:43:35.037 14496 14496 E AndroidRuntime: 	... 15 more
04-01 15:43:35.041  3656  5034 D Debug   : !@DumpState : SHIP
04-01 15:43:35.042  3656  5034 D Debug   : !@DumpState : debug level:0x4f4c
04-01 15:43:35.042  3656  5034 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
04-01 15:43:35.042  3656  5034 W ActivityManager: crash : jp.co.XXXXXX.YYYY,0
04-01 15:43:35.043  3656  5034 W ActivityManager:   Force finishing activity jp.co.XXXXXX.YYYY/.MainActivity
```

I added permissions to AndroidManifest.xml by referring to log.

```xml
<uses-permission android:name="android.permission.READ_CONTACTS" />
<uses-permission android:name="android.permission.WRITE_CONTACTS" />
```

But it's the same for the app to shut down.
I found no problems with android 4.2.2, 5.1.1, 6.0.0 and 7.1.1.

I look forward to your help.

**Comment by pavane90** [comment]
ionic cordova rm cordova-plugin-crosswalk-webview

it works :(
