### ISSUE TITLE
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

### ISSUE THREAD

**Issue by sajumani** [crosswalk-project/cordova-plugin-crosswalk-webview#252]
Hi,

When i trying to take build of My Ionic developed app with Cross Walk Plugin. It shows below error

> Executing script found in plugin cordova-plugin-crosswalk-webview for hook "before_build": plugins\cordova-plugin-crosswalk-webview\hooks\before_build\000-build_64_bit.js
> Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
> CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
>     at Context.requireCordovaModule (C:\Users\Dell\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
>     at module.exports (E:\chatapp\chatme\plugins\cordova-plugin-crosswalk-webview\hooks\before_build\000-build_64_bit.js:6:28)
>     at runScriptViaModuleLoader (C:\Users\Dell\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
>     at runScript (C:\Users\Dell\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
>     at C:\Users\Dell\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
>     at startup (internal/bootstrap/node.js:238:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
> [ERROR] An error occurred while running subprocess cordova.

**Comment by sajumani** [comment]
I think cordova-plugin-crosswalk-webview not compatible with Cordova 9
